### ISSUE TITLE
问下是否有其他办法可以替代一开始adb

### ISSUE THREAD

**Issue by chenj1ahui** [android-notes/androidScreenShareAndControl#10]
请问下是否有其他办法可以替代一开始adb呢？因为正在研究如何直接打包成apk，实现远程控制。求指点。。

**Comment by chenj1ahui** [comment]
@android-notes

**Comment by android-notes** [comment]
adb是必须的，我们能做的就是写个程序自动调用adb，免去输入命令，完全不依赖adb的话没法搞 @chenj1ahui
