### ISSUE TITLE
求教：请问如何将Main.java和相关的java类编译成一个class文件

### ISSUE THREAD

**Issue by ZhaoYidong** [android-notes/androidScreenShareAndControl#2]
编译的时候提示找不到graphics  net 等 android的一些类。
导入到AndroidStudio中，build后得不到class或者dex，只得到一个calss.jar。尝试将class.jar转为dex，结果也没成功。并且class.jar只有16k，而你提供的Main.dex有130k。总感觉不对。
可能问题有些简单，希望指教。

**Comment by android-notes** [comment]
你可以在Android studio中新建一个java lib，然后在里面编写代码，同时编写一个main类，然后运行这个main类，就会在项目工程中生成所有class文件了 @ZhaoYidong

**Comment by android-notes** [comment]
具体用到的命令参考这 http://blog.csdn.net/qingchunweiliang/article/details/69210431  @ZhaoYidong

**Comment by ZhaoYidong** [comment]
谢谢，后来是编译成 apk 后，解压 apk 得到的 dex 文件。发现是可以用的。只是会有一些冗余代码，并且 dex 文件比较大，不过可以用。您的博客对我帮助很大。谢谢 @android-notes

**Comment by android-notes** [comment]
🙂不客气 @ZhaoYidong

**Comment by jiajianma375** [comment]
参照您提到的方法，成功编译出了Main.dex文件，但是只有13k左右，尝试了一下没有顺利显示手机画面。您提供的Main.dex文件有128k大，想请问您是怎么编译的。还望看到了能帮忙解答，谢谢啦~ @android-notes

**Comment by android-notes** [comment]
你可以在Android studio中新建一个java lib，然后把代码拷贝过去，同时编写一个main类，然后右击这个文件，选择运行这个main类，就会在项目工程中生成所有class文件了@jiajianma375
